# Generated by Django 5.2.1 on 2025-05-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('profissao', models.CharField(max_length=100)),
            ],
        ),
    ]
