# Generated by Django 5.2.1 on 2025-05-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_global', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('especie', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='animais',
            field=models.ManyToManyField(to='app_global.animal'),
        ),
    ]
