# Generated by Django 5.2.1 on 2025-05-27 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_global', '0002_animal_pessoa_animais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animais'},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
    ]
